[package]
name = "buildscripts"
version = "0.0.0"
edition = "2024"

[dependencies]
buildscripts-cli = { path = "./crates/buildscripts-cli" }
buildscripts-core = { path = "./crates/buildscripts-core" }